// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzYV3Usil8yqEqkNvtTRKhJQRMJwEduhs',
    appId: '1:1041823189603:web:9846f8ed13309bbbc5c656',
    messagingSenderId: '1041823189603',
    projectId: 'flutter-firebase-cubit',
    authDomain: 'flutter-firebase-cubit.firebaseapp.com',
    storageBucket: 'flutter-firebase-cubit.appspot.com',
    measurementId: 'G-VXVT629JVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDibjC75K5bv8We_fEi2LCOvv3k_QVRg3s',
    appId: '1:1041823189603:android:479c8cef9bb368b2c5c656',
    messagingSenderId: '1041823189603',
    projectId: 'flutter-firebase-cubit',
    storageBucket: 'flutter-firebase-cubit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB49Cvgz-OVa_LQ2F0XXiXuAD-030M4XxE',
    appId: '1:1041823189603:ios:1d3ec763bf54c4bfc5c656',
    messagingSenderId: '1041823189603',
    projectId: 'flutter-firebase-cubit',
    storageBucket: 'flutter-firebase-cubit.appspot.com',
    iosClientId: '1041823189603-efdo2e4m9t184rrv855fsruaaao6h8hk.apps.googleusercontent.com',
    iosBundleId: 'com.getnerdify.firebaseCubit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB49Cvgz-OVa_LQ2F0XXiXuAD-030M4XxE',
    appId: '1:1041823189603:ios:1d3ec763bf54c4bfc5c656',
    messagingSenderId: '1041823189603',
    projectId: 'flutter-firebase-cubit',
    storageBucket: 'flutter-firebase-cubit.appspot.com',
    iosClientId: '1041823189603-efdo2e4m9t184rrv855fsruaaao6h8hk.apps.googleusercontent.com',
    iosBundleId: 'com.getnerdify.firebaseCubit',
  );
}
